# Generated by Django 4.1.2 on 2022-10-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0003_delete_user_remove_tag_tag_photo_sender_photo_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display_photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_photo', models.ImageField(upload_to='display_photos')),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='location',
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
