# Generated by Django 4.1.2 on 2023-02-27 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0005_tag_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='taken_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
