# Generated by Django 4.0.2 on 2023-03-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0006_photo_taken_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tag',
            field=models.ManyToManyField(to='photo_app.Tag'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
